# Copyright (C) 2025 Daniel López Bermúdez
# License AGPL-3.0 (https://www.gnu.org/licenses/agpl-3.0.html)

services:
  odoo:
    build: .
    container_name: odoo-project-management-education-odoo-1
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - odoo-data:/var/lib/odoo
      - ./odoo_backups:/var/lib/odoo/.local/share/Odoo/backups
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: always

  db:
    image: postgres:15
    container_name: odoo-project-management-education-db-1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: always

volumes:
  odoo-data:
  db-data:
